### ISSUE TITLE
Laravel 8 issue with legacy factories support

### ISSUE THREAD

**Issue by freestyledork** [sebastiaanluca/laravel-auto-morph-map#15] opened 2021-07-28 20:53 UTC
Using this package with laravel 8 and legacy factories throws an error when composer generates optimized autoload files.  I get the error   `Undefined variable $factory`. That makes sense if I didn't include the `laravel/legacy-factories` package, I can confirm everything loads fine once I remove this package. 

Please advise.

**Comment by sebastiaanluca** [comment] 2021-07-29 08:16
>when composer generates optimized autoload files

Can you give the full list of commands that are executed beside autoloading? And the exception full stack trace? This package doesn't hook into that command. It only maps the models when the map command is executed, then does `Relation::morphMap($map);`. It does do `new ReflectionClass($model);`, so my guess it tries to load a model that references an invalid factory variable somewhere.

Also check if it's not one the other common issues that might trigger it: https://www.google.com/search?q=laravel+Undefined+variable+%24factory. If you find some time, setting up a clean Laravel project that reproduces this bug can help us find the issue almost immediately.

**Comment by freestyledork** [comment] 2021-07-29 14:28
I can reproduce this in 4 steps.

1) Clean install of laravel 8 using composer
`composer create-project laravel/laravel local.laravel8.com`

2) Install laravel legacy factories 
`composer require laravel/legacy-factories`

3) Swap the laravel 8 UserFactory to laravel 7 default. 
```<?php

namespace Database\Factories;
/** @var \Illuminate\Database\Eloquent\Factory $factory */

use App\Models\User;
use Faker\Generator as Faker;
use Illuminate\Support\Str;

$factory->define(User::class, function (Faker $faker) {
    return [
        'name' => $faker->name,
        'email' => $faker->unique()->safeEmail,
        'email_verified_at' => now(),
        'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', // password
        'remember_token' => Str::random(10),
    ];
});
```

4) attempt to install this package
`composer require sebastiaanluca/laravel-auto-morph-map`

```
Using version ^7.0 for sebastiaanluca/laravel-auto-morph-map
./composer.json has been updated
Running composer update sebastiaanluca/laravel-auto-morph-map
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking sebastiaanluca/laravel-auto-morph-map (7.0.1)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing sebastiaanluca/laravel-auto-morph-map (7.0.1): Extracting archive
Package sebastian/resource-operations is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   ErrorException

  Undefined variable $factory

  at C:\var\www\local.laravel8.com\database\factories\UserFactory.php:10
      6▕ use App\Models\User;
      7▕ use Faker\Generator as Faker;
      8▕ use Illuminate\Support\Str;
      9▕
  ➜  10▕ $factory->define(User::class, function (Faker $faker) {
     11▕     return [
     12▕         'name' => $faker->name,
     13▕         'email' => $faker->unique()->safeEmail,
     14▕         'email_verified_at' => now(),

  1   C:\var\www\local.laravel8.com\database\factories\UserFactory.php:10
      Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Undefined variable $factory", "C:\var\www\local.laravel8.com\database\factories\UserFactory.php")

  2   C:\var\www\local.laravel8.com\vendor\composer\ClassLoader.php:444
      include("C:\var\www\local.laravel8.com\database\factories\UserFactory.php")
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

Also, when attempting other packages composer installs correctly. So I am not sure where the issue is, For example I installed Clockwork fine using the same steps. 
`composer require itsgoingd/clockwork` 

Hope this helps.

**Comment by sebastiaanluca** [comment] 2021-08-03 17:00
Thanks for the detailed response. I'll have a proper look as soon as I can.

In the mean time, can you try removing `namespace Database\Factories;` from the legacy user factory and see if that does anything? Since it's not a class, it shouldn't be namespaced.

**Comment by freestyledork** [comment] 2021-08-03 17:55
@sebastiaanluca whoops, I must have missed the namespace declaration. Anyway, after removing it the issue still persists.

**Comment by sebastiaanluca** [comment] 2022-03-01 12:22
Sorry I didn't follow up on this. I'm closing it for now as I'm planning on deprecating the package, but let me know if it's still an issue. If it is, please provide a repository that reproduces the issue so I can quickly jump in and find what's causing the bug.

**Closed as completed by sebastiaanluca** 2022-03-01 12:22 UTC
Labels: bug
